packages:
  - vite
  - example/output
  - example/react
  - example/multi_app
  - example/stderr
  - example/custom_build
  - example/svelte-in-different-dir/frontend

onlyBuiltDependencies:
  - esbuild
